In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_file_path = "../data/raw/telco_customer_churn_raw.xlsx"
raw_file_path

'../data/raw/telco_customer_churn_raw.xlsx'

In [3]:
df = pd.read_excel(raw_file_path)

In [4]:
df.shape

(7043, 33)

In [5]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [6]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='str')

In [7]:
for column in df.columns:
    print(column)

CustomerID
Count
Country
State
City
Zip Code
Lat Long
Latitude
Longitude
Gender
Senior Citizen
Partner
Dependents
Tenure Months
Phone Service
Multiple Lines
Internet Service
Online Security
Online Backup
Device Protection
Tech Support
Streaming TV
Streaming Movies
Contract
Paperless Billing
Payment Method
Monthly Charges
Total Charges
Churn Label
Churn Value
Churn Score
CLTV
Churn Reason

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 2.9+ MB

In [9]:
df.columns.tolist()

['CustomerID',
 'Count',
 'Country',
 'State',
 'City',
 'Zip Code',
 'Lat Long',
 'Latitude',
 'Longitude',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Label',
 'Churn Value',
 'Churn Score',
 'CLTV',
 'Churn Reason']

In [10]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["CustomerID"].duplicated().sum()

np.int64(0)

In [13]:
df.dtypes

CustomerID               str
Count                  int64
Country                  str
State                    str
City                     str
Zip Code               int64
Lat Long                 str
Latitude             float64
Longitude            float64
Gender                   str
Senior Citizen           str
Partner                  str
Dependents               str
Tenure Months          int64
Phone Service            str
Multiple Lines           str
Internet Service         str
Online Security          str
Online Backup            str
Device Protection        str
Tech Support             str
Streaming TV             str
Streaming Movies         str
Contract                 str
Paperless Billing        str
Payment Method           str
Monthly Charges      float64
Total Charges         object
Churn Label              str
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason             str
dtype: object

In [14]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [15]:
df.describe(include="object")

C:\Users\khali\AppData\Local\Temp\ipykernel_20288\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,CustomerID,Country,State,City,Lat Long,Gender,Senior Citizen,Partner,Dependents,Phone Service,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Total Charges,Churn Label,Churn Reason
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043.0,7043,1869
unique,7043,1,1,1129,1652,2,2,2,2,2,...,3,3,3,3,3,2,4,6531.0,2,20
top,3668-QPYBK,United States,California,Los Angeles,"33.964131, -118.272783",Male,No,No,No,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No,Attitude of support person
freq,1,7043,7043,305,5,3555,5901,3641,5416,6361,...,3095,3473,2810,2785,3875,4171,2365,11.0,5174,192

In [16]:
df["Churn Label"].value_counts()

Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

In [17]:
df["Churn Label"].value_counts(normalize=True)*100

Churn Label
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [18]:
df.columns.tolist()

['CustomerID',
 'Count',
 'Country',
 'State',
 'City',
 'Zip Code',
 'Lat Long',
 'Latitude',
 'Longitude',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Label',
 'Churn Value',
 'Churn Score',
 'CLTV',
 'Churn Reason']

In [19]:
df_clean = df.copy()

In [20]:
df_clean.columns = (df_clean.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("-", "_"))

In [21]:
df_clean.columns.tolist()

['customerid',
 'count',
 'country',
 'state',
 'city',
 'zip_code',
 'lat_long',
 'latitude',
 'longitude',
 'gender',
 'senior_citizen',
 'partner',
 'dependents',
 'tenure_months',
 'phone_service',
 'multiple_lines',
 'internet_service',
 'online_security',
 'online_backup',
 'device_protection',
 'tech_support',
 'streaming_tv',
 'streaming_movies',
 'contract',
 'paperless_billing',
 'payment_method',
 'monthly_charges',
 'total_charges',
 'churn_label',
 'churn_value',
 'churn_score',
 'cltv',
 'churn_reason']

In [22]:
df_clean["churn_label"].value_counts()

churn_label
No     5174
Yes    1869
Name: count, dtype: int64

In [23]:
df_clean["churn_value"].mean()*100

np.float64(26.536987079369588)

In [24]:
df_clean.isnull().sum()

customerid              0
count                   0
country                 0
state                   0
city                    0
zip_code                0
lat_long                0
latitude                0
longitude               0
gender                  0
senior_citizen          0
partner                 0
dependents              0
tenure_months           0
phone_service           0
multiple_lines          0
internet_service        0
online_security         0
online_backup           0
device_protection       0
tech_support            0
streaming_tv            0
streaming_movies        0
contract                0
paperless_billing       0
payment_method          0
monthly_charges         0
total_charges           0
churn_label             0
churn_value             0
churn_score             0
cltv                    0
churn_reason         5174
dtype: int64

In [25]:
missing_values = df_clean.isnull().sum()

missing_values[missing_values > 0]

churn_reason    5174
dtype: int64

In [26]:
df_clean.dtypes

customerid               str
count                  int64
country                  str
state                    str
city                     str
zip_code               int64
lat_long                 str
latitude             float64
longitude            float64
gender                   str
senior_citizen           str
partner                  str
dependents               str
tenure_months          int64
phone_service            str
multiple_lines           str
internet_service         str
online_security          str
online_backup            str
device_protection        str
tech_support             str
streaming_tv             str
streaming_movies         str
contract                 str
paperless_billing        str
payment_method           str
monthly_charges      float64
total_charges         object
churn_label              str
churn_value            int64
churn_score            int64
cltv                   int64
churn_reason             str
dtype: object

In [27]:
df_clean[["monthly_charges", "total_charges"]].head()

   monthly_charges total_charges
0            53.85        108.15
1            70.70        151.65
2            99.65         820.5
3           104.80       3046.05
4           103.70        5036.3

In [28]:
df_clean["total_charges"].dtype

dtype('O')

In [29]:
df_clean["monthly_charges"].dtype

dtype('float64')

In [30]:
df_clean[["churn_label", "churn_value", "churn_score", "churn_reason"]].head(10)

,churn_label,churn_value,churn_score,churn_reason
0,Yes,1,86,Competitor made better offer
1,Yes,1,67,Moved
2,Yes,1,86,Moved
3,Yes,1,84,Moved
4,Yes,1,89,Competitor had better devices
5,Yes,1,78,Competitor offered higher download speeds
6,Yes,1,100,Competitor offered more data
7,Yes,1,92,Competitor made better offer
8,Yes,1,77,Competitor had better devices
9,Yes,1,97,Competitor had better devices

In [31]:
df_clean["churn_label"].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [32]:
df_clean["churn_value"].unique()

array([1, 0])

In [33]:
df_clean[["tenure_months", "monthly_charges", "total_charges", "churn_value", "churn_score", "cltv"]].describe()

       tenure_months  monthly_charges  churn_value  churn_score         cltv
count    7043.000000      7043.000000  7043.000000  7043.000000  7043.000000
mean       32.371149        64.761692     0.265370    58.699418  4400.295755
std        24.559481        30.090047     0.441561    21.525131  1183.057152
min         0.000000        18.250000     0.000000     5.000000  2003.000000
25%         9.000000        35.500000     0.000000    40.000000  3469.000000
50%        29.000000        70.350000     0.000000    61.000000  4527.000000
75%        55.000000        89.850000     1.000000    75.000000  5380.500000
max        72.000000       118.750000     1.000000   100.000000  6500.000000

In [34]:
df_clean["total_charges"].head(10)

0     108.15
1     151.65
2      820.5
3    3046.05
4     5036.3
5     528.35
6      39.65
7      20.15
8    4749.15
9       30.2
Name: total_charges, dtype: object

In [35]:
df_clean[df_clean["total_charges"] == " "]

,customerid,count,country,state,city,zip_code,lat_long,latitude,longitude,gender,...,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn_label,churn_value,churn_score,cltv,churn_reason
2234,4472-LVYGI,1,United States,California,San Bernardino,92408,"34.084909, -117.258107",34.084909,-117.258107,Female,...,Two year,Yes,Bank transfer (automatic),52.55,,No,0,36,2578,NaN
2438,3115-CZMZD,1,United States,California,Independence,93526,"36.869584, -118.189241",36.869584,-118.189241,Male,...,Two year,No,Mailed check,20.25,,No,0,68,5504,NaN
2568,5709-LVOEQ,1,United States,California,San Mateo,94401,"37.590421, -122.306467",37.590421,-122.306467,Female,...,Two year,No,Mailed check,80.85,,No,0,45,2048,NaN
2667,4367-NUYAO,1,United States,California,Cupertino,95014,"37.306612, -122.080621",37.306612,-122.080621,Male,...,Two year,No,Mailed check,25.75,,No,0,48,4950,NaN
2856,1371-DWPAZ,1,United States,California,Redcrest,95569,"40.363446, -123.835041",40.363446,-123.835041,Female,...,Two year,No,Credit card (automatic),56.05,,No,0,30,4740,NaN
4331,7644-OMVMY,1,United States,California,Los Angeles,90029,"34.089953, -118.294824",34.089953,-118.294824,Male,...,Two year,No,Mailed check,19.85,,No,0,53,2019,NaN
4687,3213-VVOLG,1,United States,California,Sun City,92585,"33.739412, -117.173334",33.739412,-117.173334,Male,...,Two year,No,Mailed check,25.35,,No,0,49,2299,NaN
5104,2520-SGTTA,1,United States,California,Ben Lomond,95005,"37.078873, -122.090386",37.078873,-122.090386,Female,...,Two year,No,Mailed check,20.00,,No,0,27,3763,NaN
5719,2923-ARZLG,1,United States,California,La Verne,91750,"34.144703, -117.770299",34.144703,-117.770299,Male,...,One year,Yes,Mailed check,19.70,,No,0,69,4890,NaN
6772,4075-WKNIU,1,United States,California,Bell,90201,"33.970343, -118.171368",33.970343,-118.171368,Female,...,Two year,No,Mailed check,73.35,,No,0,44,2342,NaN
6840,2775-SEFEE,1,United States,California,Wilmington,90744,"33.782068, -118.262263",33.782068,-118.262263,Male,...,Two year,Yes,Bank transfer (automatic),61.90,,No,0,65,5188,NaN

In [36]:
df_clean["total_charges"] = pd.to_numeric(df_clean["total_charges"], errors="coerce")

In [37]:
df_clean["total_charges"].dtype

dtype('float64')

In [38]:
df_clean["total_charges"].isnull().sum()

np.int64(11)

In [39]:
df_clean[df_clean["total_charges"].isnull()]

,customerid,count,country,state,city,zip_code,lat_long,latitude,longitude,gender,...,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn_label,churn_value,churn_score,cltv,churn_reason
2234,4472-LVYGI,1,United States,California,San Bernardino,92408,"34.084909, -117.258107",34.084909,-117.258107,Female,...,Two year,Yes,Bank transfer (automatic),52.55,NaN,No,0,36,2578,NaN
2438,3115-CZMZD,1,United States,California,Independence,93526,"36.869584, -118.189241",36.869584,-118.189241,Male,...,Two year,No,Mailed check,20.25,NaN,No,0,68,5504,NaN
2568,5709-LVOEQ,1,United States,California,San Mateo,94401,"37.590421, -122.306467",37.590421,-122.306467,Female,...,Two year,No,Mailed check,80.85,NaN,No,0,45,2048,NaN
2667,4367-NUYAO,1,United States,California,Cupertino,95014,"37.306612, -122.080621",37.306612,-122.080621,Male,...,Two year,No,Mailed check,25.75,NaN,No,0,48,4950,NaN
2856,1371-DWPAZ,1,United States,California,Redcrest,95569,"40.363446, -123.835041",40.363446,-123.835041,Female,...,Two year,No,Credit card (automatic),56.05,NaN,No,0,30,4740,NaN
4331,7644-OMVMY,1,United States,California,Los Angeles,90029,"34.089953, -118.294824",34.089953,-118.294824,Male,...,Two year,No,Mailed check,19.85,NaN,No,0,53,2019,NaN
4687,3213-VVOLG,1,United States,California,Sun City,92585,"33.739412, -117.173334",33.739412,-117.173334,Male,...,Two year,No,Mailed check,25.35,NaN,No,0,49,2299,NaN
5104,2520-SGTTA,1,United States,California,Ben Lomond,95005,"37.078873, -122.090386",37.078873,-122.090386,Female,...,Two year,No,Mailed check,20.00,NaN,No,0,27,3763,NaN
5719,2923-ARZLG,1,United States,California,La Verne,91750,"34.144703, -117.770299",34.144703,-117.770299,Male,...,One year,Yes,Mailed check,19.70,NaN,No,0,69,4890,NaN
6772,4075-WKNIU,1,United States,California,Bell,90201,"33.970343, -118.171368",33.970343,-118.171368,Female,...,Two year,No,Mailed check,73.35,NaN,No,0,44,2342,NaN
6840,2775-SEFEE,1,United States,California,Wilmington,90744,"33.782068, -118.262263",33.782068,-118.262263,Male,...,Two year,Yes,Bank transfer (automatic),61.90,NaN,No,0,65,5188,NaN

In [40]:
df_clean["total_charges"] = df_clean["total_charges"].fillna(0)

In [41]:
df_clean["total_charges"].isnull().sum()

np.int64(0)

In [42]:
df_clean["total_charges"].dtype

dtype('float64')

In [43]:
df_clean["churn_reason"].isnull().sum()

np.int64(5174)

In [44]:
df_clean["churn_reason"].value_counts(dropna=False)

churn_reason
NaN                                          5174
Attitude of support person                    192
Competitor offered higher download speeds     189
Competitor offered more data                  162
Don't know                                    154
Competitor made better offer                  140
Attitude of service provider                  135
Competitor had better devices                 130
Network reliability                           103
Product dissatisfaction                       102
Price too high                                 98
Service dissatisfaction                        89
Lack of self-service on Website                88
Extra data charges                             57
Moved                                          53
Limited range of services                      44
Lack of affordable download/upload speed       44
Long distance charges                          44
Poor expertise of phone support                20
Poor expertise of online support               19
Deceased                                        6
Name: count, dtype: int64

In [ ]:
df_clean["churn_reason"] = df_clean["churn_reason"].fillna("No Churn")

In [57]:
df_clean["churn_reason"].isnull().sum()

np.int64(0)

In [58]:
df_clean["churn_reason"].value_counts()

churn_reason
No Churn                                     5174
Attitude of support person                    192
Competitor offered higher download speeds     189
Competitor offered more data                  162
Don't know                                    154
Competitor made better offer                  140
Attitude of service provider                  135
Competitor had better devices                 130
Network reliability                           103
Product dissatisfaction                       102
Price too high                                 98
Service dissatisfaction                        89
Lack of self-service on Website                88
Extra data charges                             57
Moved                                          53
Limited range of services                      44
Lack of affordable download/upload speed       44
Long distance charges                          44
Poor expertise of phone support                20
Poor expertise of online support               19
Deceased                                        6
Name: count, dtype: int64

In [59]:
df_clean["tenure_group"] = pd.cut(df_clean["tenure_months"], bins=[-1, 12, 24, 48, 72], labels=["0-12 Months", "13-24 Months", "25-48 Months", "49-72 Months"])

In [60]:
df_clean["tenure_group"].value_counts().sort_index()

tenure_group
0-12 Months     2186
13-24 Months    1024
25-48 Months    1594
49-72 Months    2239
Name: count, dtype: int64

In [61]:
df_clean["monthly_charge_group"] = pd.cut(
    df_clean["monthly_charges"],
    bins=[0, 35, 70, 120],
    labels=["Low Monthly Charge", "Medium Monthly Charge", "High Monthly Charge"]
)

In [62]:
df_clean["monthly_charge_group"].value_counts().sort_index()

monthly_charge_group
Low Monthly Charge       1735
Medium Monthly Charge    1725
High Monthly Charge      3583
Name: count, dtype: int64

In [63]:
df_clean["cltv_group"] = pd.qcut(
    df_clean["cltv"],
    q=3,
    labels=["Low CLTV", "Medium CLTV", "High CLTV"]
)

In [64]:
df_clean["cltv_group"].value_counts().sort_index()

cltv_group
Low CLTV       2348
Medium CLTV    2349
High CLTV      2346
Name: count, dtype: int64

In [66]:
df_clean[[
    "customerid",
    "tenure_months",
    "tenure_group",
    "monthly_charges",
    "monthly_charge_group",
    "cltv",
    "cltv_group",
    "churn_label",
    "churn_value"
]].head(10)

,customerid,tenure_months,tenure_group,monthly_charges,monthly_charge_group,cltv,cltv_group,churn_label,churn_value
0,3668-QPYBK,2,0-12 Months,53.85,Medium Monthly Charge,3239,Low CLTV,Yes,1
1,9237-HQITU,2,0-12 Months,70.70,High Monthly Charge,2701,Low CLTV,Yes,1
2,9305-CDSKC,8,0-12 Months,99.65,High Monthly Charge,5372,High CLTV,Yes,1
3,7892-POOKP,28,25-48 Months,104.80,High Monthly Charge,5003,Medium CLTV,Yes,1
4,0280-XJGEX,49,49-72 Months,103.70,High Monthly Charge,5340,High CLTV,Yes,1
5,4190-MFLUW,10,0-12 Months,55.20,Medium Monthly Charge,5925,High CLTV,Yes,1
6,8779-QRDMV,1,0-12 Months,39.65,Medium Monthly Charge,5433,High CLTV,Yes,1
7,1066-JKSGK,1,0-12 Months,20.15,Low Monthly Charge,4832,Medium CLTV,Yes,1
8,6467-CHFZW,47,25-48 Months,99.35,High Monthly Charge,5789,High CLTV,Yes,1
9,8665-UTDHZ,1,0-12 Months,30.20,Low Monthly Charge,2915,Low CLTV,Yes,1

In [67]:
df_clean.shape

(7043, 36)

In [68]:
missing_values_final = df_clean.isnull().sum()

missing_values_final[missing_values_final > 0]

Series([], dtype: int64)

In [69]:
df_clean["churn_label"].value_counts()

churn_label
No     5174
Yes    1869
Name: count, dtype: int64

In [70]:
df_clean["churn_value"].value_counts()

churn_value
0    5174
1    1869
Name: count, dtype: int64

In [71]:
df_clean[["tenure_group", "monthly_charge_group", "cltv_group"]].head(10)

   tenure_group   monthly_charge_group   cltv_group
0   0-12 Months  Medium Monthly Charge     Low CLTV
1   0-12 Months    High Monthly Charge     Low CLTV
2   0-12 Months    High Monthly Charge    High CLTV
3  25-48 Months    High Monthly Charge  Medium CLTV
4  49-72 Months    High Monthly Charge    High CLTV
5   0-12 Months  Medium Monthly Charge    High CLTV
6   0-12 Months  Medium Monthly Charge    High CLTV
7   0-12 Months     Low Monthly Charge  Medium CLTV
8  25-48 Months    High Monthly Charge    High CLTV
9   0-12 Months     Low Monthly Charge     Low CLTV

In [72]:
df_clean["tenure_group"].value_counts().sort_index()

tenure_group
0-12 Months     2186
13-24 Months    1024
25-48 Months    1594
49-72 Months    2239
Name: count, dtype: int64

In [74]:
df_clean["monthly_charge_group"].value_counts().sort_index()

monthly_charge_group
Low Monthly Charge       1735
Medium Monthly Charge    1725
High Monthly Charge      3583
Name: count, dtype: int64

In [75]:
df_clean["cltv_group"].value_counts().sort_index()

cltv_group
Low CLTV       2348
Medium CLTV    2349
High CLTV      2346
Name: count, dtype: int64

In [76]:
df_clean[[
    "tenure_months",
    "monthly_charges",
    "total_charges",
    "churn_value",
    "churn_score",
    "cltv"
]].describe()

,tenure_months,monthly_charges,total_charges,churn_value,churn_score,cltv
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,32.371149,64.761692,2279.734304,0.265370,58.699418,4400.295755
std,24.559481,30.090047,2266.794470,0.441561,21.525131,1183.057152
min,0.000000,18.250000,0.000000,0.000000,5.000000,2003.000000
25%,9.000000,35.500000,398.550000,0.000000,40.000000,3469.000000
50%,29.000000,70.350000,1394.550000,0.000000,61.000000,4527.000000
75%,55.000000,89.850000,3786.600000,1.000000,75.000000,5380.500000
max,72.000000,118.750000,8684.800000,1.000000,100.000000,6500.000000

In [78]:
df_clean.to_csv("../data/processed/telco_customer_churn_cleaned.csv", index=False)